import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import NavBar from "@/components/interface/navbar";
import Footer from "@/components/interface/footer";


export const metadata: Metadata = {
  title: "Multiclinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>

        <NavBar />

        {children}

        <div className="fixed right-0 bottom-0 flex w-24 p-4 hover:drop-shadow-lg hover:scale-95">
          <Link href={'/'}>
            <Image src={'/icons/whatsapp.svg'} alt="logo whatsapp" width={256} height={259} />
          </Link>
        </div>

        <Footer />

      </body>
    </html>
  );
}
